repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-symlinks
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        exclude: >-
          ^plugin/.*.$
  - repo: local
    hooks:
      - id: golangci-lint
        name: Run golangci-lint
        language: system
        entry: golangci-lint run --fix
        types: [go]
        pass_filenames: false
