version: 2.1

orbs:
  bitcart: bitcart/bitcart-shared@2

commands:
  install-lint-dependencies:
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-lint-dependencies-{{ .Branch }}

      - run:
          name: Install dependencies
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.62.2

      - save_cache:
          paths:
            - /usr/local/bin/golangci-lint
          key: v1-lint-dependencies-{{ .Branch }}

jobs:
  deploy:
    executor: bitcart/docker-go

    resource_class: large

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build and publish Go CLI
          command: |
            curl -sfL https://goreleaser.com/static/run | bash

      - store_artifacts:
          path: dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - bitcart/lint:
          name: lint
          executor: bitcart/docker-go
          pre-commit-pip: false
          pre-steps:
            - install-lint-dependencies

      - deploy:
          context: global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
